Update _state.py
If I do not edit/change the revision value into 1, it will work. else it causes error
"fb_dtsg = FB_DTSG_REGEX.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'"